version: '2'
services:
    yoda:
        image: yoda
        build: .
        container_name: YodaServer
        entrypoint: /usr/local/bin/python server.py
        ports:
            - "5000:5000"
        volumes:
            - .:/app
    redis:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - ./data:/data
